FROM farrion/python3-ml:latest

LABEL maintainer="Mitesh Patel <mitpatel@redhat.com>"

COPY ./requirements.txt /requirements.txt

RUN pip3 install --upgrade pip

RUN pip3 install git+https://github.com/grikbi/infra-adapter#egg=rudra

RUN pip3 install -r requirements.txt

RUN pip3 install Cython==0.29.1 && pip3 install hpfrec==0.2.2.9

COPY ./entrypoint.sh /bin/entrypoint.sh

COPY ./src /src

# --------------------------------------------------------------------------------------------------
# copy testing source code and scripts into root dir /
# --------------------------------------------------------------------------------------------------
ADD ./training/ /training
ADD ./tests/ /tests
# ADD ./.git/ /.git
ADD ./tests/scripts/entrypoint-test.sh /entrypoint-test.sh
RUN chmod 0777 /entrypoint-test.sh

ENV PYTHONPATH=/
ENV USE_CLOUD_SERVICES="false"
ENV LOCAL_ACCESS="false"

RUN pip3 install pytest pytest-cov radon==2.4.0 faker mock

# --------------------------------------------------------------------------------------------------
# RUN THE UNIT TESTS
# --------------------------------------------------------------------------------------------------
ENTRYPOINT ["/entrypoint-test.sh"]
